#!/bin/bash
set -o pipefail

if [[ "${INPUT_FILE_PATH}" == "" ]]; then
  echo 'error: This tool only works as a build rule script'
  exit 1
fi

case "${INPUT_FILE_PATH}" in
  *.storyboard)
    OUTPUT_EXTENSION=storyboardc
    ;;
  *.xib)
    OUTPUT_EXTENSION=nib
    ;;
esac

OUTPUT_PATH="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/${INPUT_FILE_BASE}.${OUTPUT_EXTENSION}"

IBTOOL_PATH="${DEVELOPER_BIN_DIR}/ibtool"
IBTOOL_CHECKSUM="$(cksum "${IBTOOL_PATH}" | cut -d' ' -f1)"
INPUT_FILE_CHECKSUM="$(shasum "${INPUT_FILE_PATH}" | cut -d' ' -f1)"
INPUT_CONTENT_KEY="${INPUT_FILE_BASE}-v${IBTOOL_CHECKSUM}-sha1-${INPUT_FILE_CHECKSUM}"

CACHE_DIR="${HOME}/.ibtool-cache"
[ ! -d  "${CACHE_DIR}" ] && mkdir -p "${CACHE_DIR}"

OUTPUT_HASHED_TEXT_PATH="${CACHE_DIR}/${INPUT_CONTENT_KEY}.txt"
OUTPUT_HASHED_NIB_PATH="${CACHE_DIR}/${INPUT_CONTENT_KEY}.${OUTPUT_EXTENSION}"

if [ -f "${OUTPUT_HASHED_NIB_PATH}" ] && [ -f "${OUTPUT_HASHED_TEXT_PATH}" ]; then
  # Hash unchanged, no need to run 'ibtool'
  cp -fR "${OUTPUT_HASHED_NIB_PATH}" "${OUTPUT_PATH}"
  cat "${OUTPUT_HASHED_TEXT_PATH}"
  exit 0
fi

case "${TARGETED_DEVICE_FAMILY:-}" in
  1,2)
    TARGET_DEVICE_ARGS="--target-device ipad --target-device iphone"
    ;;
  1)
    TARGET_DEVICE_ARGS="--target-device iphone"
    ;;
  2)
    TARGET_DEVICE_ARGS="--target-device ipad"
    ;;
  3)
    TARGET_DEVICE_ARGS="--target-device tv"
    ;;
  4)
    TARGET_DEVICE_ARGS="--target-device watch"
    ;;
  *)
    TARGET_DEVICE_ARGS="--target-device mac"
    ;;
esac

export IBToolNeverDeque=1 # so that it doesn't hang in `ibtoold``
export XCODE_DEVELOPER_USR_PATH="${DEVELOPER_BIN_DIR}/.."
"${DEVELOPER_BIN_DIR}/ibtool" \
  --errors --warnings --notices \
  --module "${PRODUCT_MODULE_NAME}" \
  --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} \
  --output-format human-readable-text --auto-activate-custom-fonts \
  --compile "${OUTPUT_PATH}" "$INPUT_FILE_PATH" \
  ${TARGET_DEVICE_ARGS} 2> /dev/null | tee "${OUTPUT_HASHED_TEXT_PATH}"

cp -R "${OUTPUT_PATH}" "${OUTPUT_HASHED_NIB_PATH}"
